In [1]:
import numpy as np 
import pandas as pd
pd.set_option('display.max_columns', 500)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/airline-delay-and-cancellation-data-2009-2018/2011.csv
/kaggle/input/airline-delay-and-cancellation-data-2009-2018/2013.csv
/kaggle/input/airline-delay-and-cancellation-data-2009-2018/2015.csv
/kaggle/input/airline-delay-and-cancellation-data-2009-2018/2014.csv
/kaggle/input/airline-delay-and-cancellation-data-2009-2018/2009.csv
/kaggle/input/airline-delay-and-cancellation-data-2009-2018/2017.csv
/kaggle/input/airline-delay-and-cancellation-data-2009-2018/2012.csv
/kaggle/input/airline-delay-and-cancellation-data-2009-2018/2010.csv
/kaggle/input/airline-delay-and-cancellation-data-2009-2018/2018.csv
/kaggle/input/airline-delay-and-cancellation-data-2009-2018/2016.csv


In [11]:
DATA_PATH = "/kaggle/input/airline-delay-and-cancellation-data-2009-2018/"

In [5]:
# check input data
for file_name in sorted(os.listdir(DATA_PATH)):
    file_path = f"{DATA_PATH}/{file_name}"
    print(file_name)
    data = pd.read_csv(file_path)
    print(f"shape: {data.shape}")
    print(f"columns: {data.columns}")

2009.csv
shape: (6429338, 28)
columns: Index(['FL_DATE', 'OP_CARRIER', 'OP_CARRIER_FL_NUM', 'ORIGIN', 'DEST',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF',
       'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'CARRIER_DELAY',
       'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY',
       'Unnamed: 27'],
      dtype='object')
2010.csv
shape: (6450117, 28)
columns: Index(['FL_DATE', 'OP_CARRIER', 'OP_CARRIER_FL_NUM', 'ORIGIN', 'DEST',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF',
       'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'CARRIER_DELAY',
       'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY',

In [69]:
data.isna().sum()

FL_DATE                      0
OP_CARRIER                   0
OP_CARRIER_FL_NUM            0
ORIGIN                       0
DEST                         0
CRS_DEP_TIME                 0
DEP_TIME                112317
DEP_DELAY               117234
TAXI_OUT                115830
WHEELS_OFF              115829
WHEELS_ON               119246
TAXI_IN                 119246
CRS_ARR_TIME                 0
ARR_TIME                119245
ARR_DELAY               137040
CANCELLED                    0
CANCELLATION_CODE      7096862
DIVERTED                     0
CRS_ELAPSED_TIME            10
ACTUAL_ELAPSED_TIME     134442
AIR_TIME                134442
DISTANCE                     0
CARRIER_DELAY          5860736
WEATHER_DELAY          5860736
NAS_DELAY              5860736
SECURITY_DELAY         5860736
LATE_AIRCRAFT_DELAY    5860736
Unnamed: 27            7213446
dtype: int64

In [48]:
sample = train.sample(10_000, random_state=42)

X = pd.get_dummies(sample.drop(columns=["DEP_DELAY"]).set_index("FL_DATE"))
Y = sample["DEP_DELAY"] # Total Delay on Departure in minutes
Y = (sample["DEP_DELAY"] >= 0).astype(int)

In [88]:
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

X = X.select_dtypes(include=numerics)
model = make_pipeline(StandardScaler(), LinearRegression())
cross_val_score(model, X, sample["DEP_DELAY"], scoring="neg_mean_absolute_error")

array([-27.95770985, -28.09473375, -29.18152332, -28.85155431,
       -27.94089825])

In [71]:
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

lr = LogisticRegression()

model = make_pipeline(StandardScaler(), LogisticRegression())
cross_val_score(model, X, Y,)

array([0.661 , 0.6815, 0.6485, 0.663 , 0.649 ])

In [51]:
from lightgbm.sklearn import LGBMClassifier

booster = LGBMClassifier()
cross_val_score(booster, X, Y,)

array([0.866 , 0.8705, 0.8625, 0.868 , 0.864 ])

In [75]:
X = pd.get_dummies(sample.drop(columns=["DEP_DELAY"]).set_index("FL_DATE"))
Y = sample["DEP_DELAY"]

from lightgbm.sklearn import LGBMRegressor

booster = LGBMRegressor()
-cross_val_score(booster, X, Y, scoring="neg_mean_absolute_error")

array([6.36458232, 7.70410725, 8.12521282, 7.72292006, 7.06083207])

In [8]:
import boto3
session = boto3.session.Session()
s3 = session.client(
    service_name='s3',
    endpoint_url='https://storage.yandexcloud.net'
)


In [24]:
from tqdm.auto import tqdm

# hold only useful columns
columns = ['FL_DATE',
 'OP_CARRIER',
 'OP_CARRIER_FL_NUM',
 'ORIGIN',
 'DEST',
 'CRS_DEP_TIME',
 'DEP_TIME',
 'DEP_DELAY',
 'TAXI_OUT',
 'WHEELS_OFF',
 'WHEELS_ON',
 'TAXI_IN',
 'CRS_ARR_TIME',
 'ARR_TIME',
 'ARR_DELAY',
 'CANCELLED',
 'DIVERTED',
 'CRS_ELAPSED_TIME',
 'ACTUAL_ELAPSED_TIME',
 'AIR_TIME',
 'DISTANCE']
for file_name in tqdm(sorted(os.listdir(DATA_PATH))):
    file_path = f"{DATA_PATH}/{file_name}"
    data = pd.read_csv(file_path)
    
    # drop rows with NA target
    data.dropna(inplace=True, axis=0, subset=["DEP_DELAY"])
    
    # add 5 years to simulate nowadays data
    data["FL_DATE"] = pd.to_datetime(data["FL_DATE"]) + pd.to_timedelta(365 * 5, unit="days")
    data = data[data["FL_DATE"].dt.year == data["FL_DATE"].dt.year.mode()[0]]
    year = pd.to_datetime(data["FL_DATE"]).dt.year.mode()[0]
    
    # print some info
    print(file_name, data.shape, list(data.columns))

    # select only useful columns
    data = data[columns]
    
    # form new name of file
    new_file = f"{year}.parquet"
    
    # writing temp parquet file 
    data.to_parquet("data.parquet", index=False)
    
    print("uploading data to s3...")
    s3.upload_file("data.parquet", "slava-otus", f"final_project/features/{new_file}")
    forDeletion = [{'Key': f"final_project/features/{file_name}"}]
    response = s3.delete_objects(Bucket='slava-otus', Delete={'Objects': forDeletion})

  0%|          | 0/10 [00:00<?, ?it/s]

2009.csv (6330384, 28) ['FL_DATE', 'OP_CARRIER', 'OP_CARRIER_FL_NUM', 'ORIGIN', 'DEST', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF', 'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME', 'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY', 'Unnamed: 27']
{'ACTUAL_ELAPSED_TIME', 'FL_DATE', 'DEP_TIME', 'TAXI_OUT', 'OP_CARRIER', 'CRS_ARR_TIME', 'Unnamed: 27', 'LATE_AIRCRAFT_DELAY', 'WHEELS_OFF', 'CRS_ELAPSED_TIME', 'DIVERTED', 'WEATHER_DELAY', 'AIR_TIME', 'ARR_TIME', 'CANCELLED', 'CANCELLATION_CODE', 'ARR_DELAY', 'TAXI_IN', 'DISTANCE', 'DEST', 'DEP_DELAY', 'CARRIER_DELAY', 'OP_CARRIER_FL_NUM', 'ORIGIN', 'CRS_DEP_TIME', 'SECURITY_DELAY', 'NAS_DELAY', 'WHEELS_ON'}
uploading data...
2010.csv (6326323, 28) ['FL_DATE', 'OP_CARRIER', 'OP_CARRIER_FL_NUM', 'ORIGIN', 'DEST', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAX